export { default as Contact } from './Contact'
export { default as Projects } from './Projects'
export { default as School } from './School'
export { default as Skills } from './Skills'
export { default as Work } from './Work'
